package com.example.classactivity8

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.Toast
import com.example.classactivity8.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {

    // private - var, val (final)
    private lateinit var buttonGo : Button // lateinit - will assign value before use
    private lateinit var editTextName : EditText

    // binding class name autogenerated - camel case
    private lateinit var binding : ActivityMainBinding

    private lateinit var buttonVillager : Button

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        /**
        setContentView(R.layout.activity_main)
        buttonGo = findViewById(R.id.button_go)
        editTextName = findViewById(R.id.editText_name)
        */

        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root) // connects to all the views in this layout
        buttonGo = binding.buttonGo
        editTextName = binding.editTextName
        buttonVillager = binding.buttonVillagers

        buttonGo.setOnClickListener {
            //toastInput("Hello, " + editTextName.text.toString())
            launchSecondActivity(editTextName.text.toString())
        }
        buttonVillager.setOnClickListener {
            launchThirdActivity()
        }
    }


    private fun toastInput(text : String){
        Toast.makeText(this, text, Toast.LENGTH_LONG).show()
    }

    private fun launchSecondActivity(message: String){
        val intent = Intent(this, SecondActivity::class.java) // standards
        intent.putExtra("name", message)
        startActivity(intent)
    }

    private fun launchThirdActivity(){
        val intent = Intent(this, ThirdActivity::class.java)
        startActivity(intent)
    }
}